# Generated by Django 4.2.3 on 2023-07-24 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargoFuncao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Carreia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conclusaoCurso', models.DateField()),
                ('despacho', models.DateField()),
                ('visto', models.DateField()),
                ('observacao', models.TextField()),
                ('cargoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep7.cargofuncao')),
                ('carreiraId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep7.carreia')),
            ],
        ),
        migrations.CreateModel(
            name='Escalao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EspecialidadeMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Financiamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NivelOcupacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Regime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoPerda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoVinculacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('password', models.CharField(max_length=128)),
                ('roleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep7.role')),
            ],
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('despacho', models.DateField()),
                ('visto', models.DateField()),
                ('iniciativaFuncionario', models.TextField()),
                ('entradaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep7.entrada')),
                ('perdaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep7.tipoperda')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('sexo', models.CharField(max_length=1)),
                ('data_nascimento', models.DateField()),
                ('nacionalidade', models.TextField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep7.user')),
            ],
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('distritoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep7.distrito')),
            ],
        ),
        migrations.AddField(
            model_name='entrada',
            name='entradaId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep7.tipoentrada'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='escalaoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep7.escalao'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='especialidadeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep7.especialidademedica'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='estabelecimentoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep7.estabelecimento'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='financiamentoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep7.financiamento'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='pessoalId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep7.pessoa'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='sectorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep7.sector'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='vinculacaoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep7.tipovinculacao'),
        ),
        migrations.CreateModel(
            name='EntidadePessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidadeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep7.entidade')),
                ('pessoaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep7.pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='distrito',
            name='provinciaId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep7.provincia'),
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('carreiraId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep7.carreia')),
            ],
        ),
        migrations.AddField(
            model_name='carreia',
            name='ocupacaoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep7.nivelocupacao'),
        ),
        migrations.AddField(
            model_name='carreia',
            name='regimeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep7.regime'),
        ),
    ]
